In [8]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt 

In [2]:
revenue=np.array([[100,200,220],[24,36,48],[12,18,20]])
expenses=np.array([[80,90,100],[10,16,20],[8,10,10]])

In [3]:
profit=revenue-expenses
profit

array([[ 20, 110, 120],
       [ 14,  20,  28],
       [  4,   8,  10]])

In [4]:
price_per_unit=np.array([1000,400,1200])
units=np.array([[30,40,50],[5,10,15],[2,5,7]])

In [9]:
df =pd.read_csv("housing_data.csv")
df

area  bedrooms   price
0   1056.0       2.0   39.07
1   2600.0       4.0  120.00
2   1440.0       3.0   62.00
3   1521.0       3.0   75.00
4   1200.0       2.0   51.00
5   1170.0       2.0   38.00
6   2732.0       4.0  135.00
7   3300.0       4.0  155.00
8   3700.0       5.0  167.00
9   1800.0       3.0   82.00
10  2785.0       4.0  140.00
11  1000.0       2.0   38.00
12  1100.0       2.0   40.00
13  2250.0       3.0  101.00
14  1175.0       2.0   42.00
15  1180.0       3.0   48.00
16  1540.0       3.0   60.00
17  2770.0       3.0  102.00

In [12]:
from sklearn import preprocessing 
sx=preprocessing.MinMaxScaler()
sy=preprocessing.MinMaxScaler()
scaled_X=sx.fit_transform(df.drop('price',axis='columns'))
scaled_X



array([[0.02074074, 0.        ],
       [0.59259259, 0.66666667],
       [0.16296296, 0.33333333],
       [0.19296296, 0.33333333],
       [0.07407407, 0.        ],
       [0.06296296, 0.        ],
       [0.64148148, 0.66666667],
       [0.85185185, 0.66666667],
       [1.        , 1.        ],
       [0.2962963 , 0.33333333],
       [0.66111111, 0.66666667],
       [0.        , 0.        ],
       [0.03703704, 0.        ],
       [0.46296296, 0.33333333],
       [0.06481481, 0.        ],
       [0.06666667, 0.33333333],
       [0.2       , 0.33333333],
       [0.65555556, 0.33333333]])

In [13]:
scaled_Y=sy.fit_transform(df['price'].values.reshape(df.shape[0],1))
scaled_Y

array([[0.00829457],
       [0.63565891],
       [0.18604651],
       [0.28682171],
       [0.10077519],
       [0.        ],
       [0.75193798],
       [0.90697674],
       [1.        ],
       [0.34108527],
       [0.79069767],
       [0.        ],
       [0.01550388],
       [0.48837209],
       [0.03100775],
       [0.07751938],
       [0.17054264],
       [0.49612403]])

In [ ]:
def batch_gradient_descent(X,y_true,epochs,learning_rate=0.01):
    number_of_features=X.shape[1]
    weights=np.ones(number_of_features)
    b=0
    total_samples=X.shape[0]
    for i in range(epochs):
        y_predicted=np.dot(weights,scaled_X.T)+b
        w_grad=-(2/total_samples)*(X.T.dot(y_true-y_predicted))
        b_grad=-(2/total_samples)*np.sum(y_true-y_predicted)